CREATE DATABASE blog_project;

USE blog_project;

CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(100) UNIQUE,
password VARCHAR(255),
role VARCHAR(20) DEFAULT 'user'
);

CREATE TABLE posts(
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255),
content TEXT
);